### ISSUE TITLE
Countdown timer hogs resources

### ISSUE THREAD

**Issue by JamielVanEngen** [RogierGrobbee/Eenmaalandermaal#1]
The timer in the the function refreshVeilingTijd (countdown.js) will trigger the garbage collector every time the setInterval function is called. Because the setInterval function is called every second it slows the page down FAST.

**Comment by JamielVanEngen** [comment]
The issue was fixed by replacing the setInterval function with the setTimeout function.

**Comment by leonchen7498** [comment]
wat leuk
